web_module/myids/urls.py
from django.urls import path
from . import views


app_name = 'myids'
urlpatterns = [
    path('', views.view_index, name='index'),
    path('stat', views.view_stat, name='stat'),
    path('conn', views.view_conn, name='conn'),
    path('query_conn', views.query_conn, name='query_conn'),
    path('query_stat', views.query_stat, name='query_stat'),
]

web_module/web_module/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('myids/', include('myids.urls'))
]

web_module/myids/models.py
from django.db import models

# Create your models here.

web_module/myids/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, JsonResponse
from django.template import loader
import datetime
import json
import importlib

# Create your views here.

##################
# Page rendering #
##################
def view_index(request):
    context = {}
    data_types = ['alert', 'proto', 'src_ip', 'dest_ip', 'src_port', 'dest_port']
    time_context = set_time(request)
    context.update(time_context)
    context['data_types'] = data_types
    return render(request, 'myids/index.html', context)


def view_stat(request):
    context = {}
    data_types = ['alert', 'proto', 'src_ip', 'dest_ip', 'src_port', 'dest_port']
    time_context = set_time(request)
    context.update(time_context)
    context['data_types'] = data_types
    return render(request, 'myids/stat.html', context)


def view_conn(request):
    condition = request.GET.get("condition", "null")
    context = {
        "condition": condition, 
    }
    time_context = set_time(request)
    context.update(time_context)
    return render(request, 'myids/conn.html', context)


#########################
# Response without page #
#########################
@csrf_exempt
def query_conn(request):
    if request.GET:
        req = request.GET['req']
        conn = importlib.import_module(".dbutil.conn", package="myids")
        if req == "data":
            condition = request.GET['condition']
            condition = condition.replace('@', "'")
            condition = None if condition == "null" else condition
            page_id = int(request.GET['page_id'])
            page_size = int(request.GET['page_size'])
            from_time = request.GET['from_time']
            to_time = request.GET['to_time']
            data_and_count = conn.get(page_id=page_id, page_size=page_size, from_time=from_time, to_time=to_time, condition=condition)
            resp_content = {}
            resp_content.update(data_and_count)
        elif req == "cols":
            cols = conn.get_cols()
            cols = [rec[0] for rec in cols]
            resp_content = {
                "cols": cols
            }
        return JsonResponse(
                resp_content, 
                encoder=JsonCustomEncoder, 
                status='200')
    else:
        return HttpResponse(content="error", charset='utf-8', status='404')
    

def query_stat(request):
    if request.GET:
        form = request.GET
        data_type = form["data_type"]
        requester = form["requester"]
        from_time, to_time = form.get('from_time'), form.get('to_time')
        db_module = importlib.import_module(".dbutil." + data_type, package="myids")

        if requester == "pie":
            data = db_module.get_count(from_time=from_time, to_time=to_time)
            resp_content = {
                "series": data
            }

        elif requester == "line":
            xAxis = []
            distinct = db_module.get_count(from_time=from_time, to_time=to_time)
            distinct = tuple(rec[0] for rec in distinct)
            raw_data = {}
            for entry in distinct:
                raw_data[entry] = []
            from_day, to_day = from_time[:10], to_time[:10]
            t = datetime.datetime.strptime(from_day + " 00:00:00", "%Y-%m-%d %H:%M:%S")
            end_t = datetime.datetime.strptime(to_day + " 23:59:59", "%Y-%m-%d %H:%M:%S")
            one_day = datetime.timedelta(days=1)
            while t < end_t:
                xAxis_time = t.strftime("%m-%d")
                xAxis.append(xAxis_time)
                query_from_time = t.strftime("%Y-%m-%d %H:%M:%S")
                t += one_day
                query_to_time = t.strftime("%Y-%m-%d %H:%M:%S")
                day_data = db_module.get_count(from_time=query_from_time, to_time=query_to_time, specific=distinct)
                unrecorded_keys = list(distinct)
                for record in day_data:
                    entry, count = record[0], record[1]
                    raw_data[entry].append(count)
                    unrecorded_keys.remove(entry)
                for entry in unrecorded_keys:
                    raw_data[entry].append(0)
            data = []
            for name, data_series in raw_data.items():
                data.append({'name': name, 'data': data_series})
            resp_content = {
                "series": data, 
                "xAxis": xAxis,
            }

        elif requester == "stat_overview":
            page_id, page_size = int(form.get("page_id")), int(form.get("page_size"))
            data_and_count = db_module.get_stat_by(page_size=page_size, page_id=page_id, from_time=from_time, to_time=to_time)
            cols = ["conn count", "alert", "proto", "src_ip", "src_port", "dest_ip", "dest_port", "service"]
            cols.remove(data_type)
            cols[0:0] = [data_type]
            resp_content = {
                "cols": cols
            }
            resp_content.update(data_and_count)

        elif requester == "stat_detail":
            condition_value = form.get("data_value")
            stat_type = form.get("stat_type")
            page_id, page_size = int(form.get("page_id")), int(form.get("page_size"))
            data_and_count = db_module.get_specific_stat_by(
                condition_value, stat_type, page_size=page_size, page_id=page_id, from_time=from_time, to_time=to_time
            )
            cols = [stat_type, "count", "earlieat occurence", "last occurence"]
            resp_content = {
                "cols": cols
            }
            resp_content.update(data_and_count)

        else:
            data = None
            resp_content = {
                "data": data
            }
        
        return JsonResponse(
                resp_content, 
                encoder=JsonCustomEncoder, 
                status='200')
    else:
        return HttpResponse(content="error", charset='utf-8', status='404')


###########
# Helpers #
###########
class JsonCustomEncoder(json.JSONEncoder):
    def default(self, field):
        if isinstance(field, datetime.datetime):
            return field.strftime('%Y-%m-%d %H:%M:%S')
        # elif isinstance(field, date):
        #     return field.strftime('%Y-%m-%d')
        elif isinstance(field, bytes):
            if field == b'0':
                return 0
            elif field == b'1':
                return 1 
        else:
            return list(json.JSONEncoder.default(self, field))


def set_time(request):
    if (request.POST):
        p = request.POST
        start_time = p["from-year"] + '-' + p["from-month"] + '-' + p["from-day"] + \
            ' ' + p["from-hour"] + ':' + p["from-minute"] + ':' + p["from-second"]
        end_time = p["to-year"] + '-' + p["to-month"] + '-' + p["to-day"] + \
            ' ' + p["to-hour"] + ':' + p["to-minute"] + ':' + p["to-second"]
    elif request.GET:
        start_time = request.GET.get("from_time", "null")
        end_time = request.GET.get("to_time", "null")
    else:
        end_time = datetime.datetime.now()
        start_time = end_time - datetime.timedelta(days=30)
        start_time = start_time.strftime("%Y-%m-%d %H:%M:%S")
        end_time = end_time.strftime("%Y-%m-%d %H:%M:%S")
    context = {
        'start_time': start_time, 
        'end_time': end_time, 
    }
    return context

web_module/myids/templates/myids/condition.html
<div class="condition-container">
    <span class="border-title">Search filter</span>

    <div class="added-container">
        <span class="border-title">Added conjunction</span>
        <div class="added-conjunction"></div>
        <button class="add-condition-button">Submit query condition</button>
    </div>
    
    <div class="added-container">
        <span class="border-title">Added atomic</span>
        <div class="added-atomic"></div>
        <button class="add-conjunction-button">Add Conjunction</button>
    </div>

    <div class="to-add-atomic-condition">
        <table class="add-atomic-table">
            <tr>
                <td>col</td>
                <td>operator</td>
                <td>compared value</td>
            </tr>
            <tr>
                <td>
                    <select class="select-cols"></select>
                </td>
                <td>
                    <select class="select-operator">
                        <option>=</option>
                        <option>&lt</option>
                        <option>&gt</option>
                        <option>&lt=</option>
                        <option>&gt=</option>
                        <option>IN</option>
                    </select>
                </td>
                <td><input class="cmp-value-input"></td>
            </tr>
        </table>
        <button class="add-atomic-button">Add atomic</button>
    </div>
</div>
<button class="panel-control-button">SEARCH</button>

web_module/myids/templates/myids/conn.html
{% load static %}
<html>
    <head>
        <title>myids</title>
        <link rel="stylesheet" type="text/css" href="{% static 'myids/css/highcharts.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'myids/css/header.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'myids/css/mainbody-title.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'myids/css/table.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'myids/css/pagin.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'myids/css/condition.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'myids/css/conn.css' %}">

        <script src="{% static 'myids/js/resource/jquery.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'myids/js/resource/highcharts.js' %}" type="text/javascript"></script>

        <script src="{% static 'myids/js/select_datetime.js' %}" type="text/javascript"></script>
        <script>
            var condition = "{{condition}}";
            condition = condition == "null" ? null : condition;
            var start_time = "{{start_time}}";
            var end_time = "{{end_time}}";
            var page_data_url = "{% url 'myids:query_conn' %}";
            var page_size = 10;
        </script>
        <script src="{% static 'myids/js/conn.js' %}" type="text/javascript"></script>
        <script src="{% static 'myids/js/conn-condition.js' %}" type="text/javascript"></script>
        <script src="{% static 'myids/js/pagin.js' %}" type="text/javascript"></script>
    </head>

    <body>
        
        <!-- header -->
        {% include 'myids/header.html' %}

        <!--main body-->
        {% include 'myids/mainbody-title.html' with title_name='Connection' query_url='myids:conn' %}
        {% include 'myids/condition.html' %}

        <div id="mainbody-table-container">
            <table>
                <thead>
                    <tr>
                        <th>Time</th>
                        <th>Protocol</th>
                        <th>Src_ip</th>
                        <th>Src_port</th>
                        <th>Dest_ip</th>
                        <th>Dest_port</th>
                        <th>Service</th>
                        <th>Duration</th>
                        <th>Orig_bytes</th>
                        <th>Resp_bytes</th>
                        <th>Orig_packets</th>
                        <th>Resp_packets</th>
                        <th>alert</th>
                    </tr>
                </thead>
                <tbody id="mainbody-table-body"></tbody>
            </table>
            <div id="mainbody-pagination"></div>
        </div>
        
    </body>
</html>

web_module/myids/templates/myids/header.html
<div id="header">
    <h1 id='header-title'>MYIDS</h1>
    <div id="header-nav">
        <ul>
            <a class="header-nav-link" href="{% url 'myids:index' %}">
                <li class='header-nav-item' id="overview-link">
                    Overview
                </li>
            </a>
            <a class="header-nav-link" href="{% url 'myids:stat' %}">
                <li class='header-nav-item' id="statistic-link">
                    Statistic
                </li>
            </a>
            <a class="header-nav-link" href="{% url 'myids:conn' %}">
                <li class='header-nav-item' id="connection-link">
                    Connection
                </li>
            </a>
        </ul>
    </div>
</div>

web_module/myids/templates/myids/index.html
{% load static %}
<html>
    <head>
        <title>myids</title>
        <link rel="stylesheet" type="text/css" href="{% static 'myids/css/highcharts.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'myids/css/header.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'myids/css/mainbody-title.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'myids/css/index.css' %}">

        <script src="{% static 'myids/js/resource/jquery.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'myids/js/resource/highcharts.js' %}" type="text/javascript"></script>

        <script src="{% static 'myids/js/render.js' %}" type="text/javascript"></script>
        <script src="{% static 'myids/js/queryStat.js' %}" type="text/javascript"></script>
        <script src="{% static 'myids/js/select_datetime.js' %}" type="text/javascript"></script>
        <script>
            var start_time = "{{start_time}}";
            var end_time = "{{end_time}}";
            var query_stat_url = "{% url 'myids:query_stat' %}";
        </script>
    </head>
    <body>
        
        <!-- header -->
        {% include 'myids/header.html' %}

        <!--main body-->
        {% include 'myids/mainbody-title.html' with title_name='Current Overview' query_url='myids:index' %}
        
        <div id="mainbody-panels">
            {% for data_type in data_types %}
                <div class='chart-container'>
                    <div class='chart-title'>
                        <div class='chart-title-text'>{{data_type}} (top 10)</div>
                        <a class='chart-title-link'>more stats...</a>
                    </div>
                    <div class="pie-container" id="{{data_type}}-pie-container">
                        <script>
                            loadPie("{{data_type}}-pie-container", "{{data_type}}", start_time, end_time);
                        </script>
                    </div>
                </div>
            {% endfor %}
        </div>

    </body>
</html>

web_module/myids/templates/myids/mainbody-title.html
<div id="mainbody-title">
    <div id="mainbody-title-left">
        <h1 id="mainbody-title-text">{{title_name}}</h1>
        <h4 id="mainbody-title-timeline">Queried from {{start_time}} to {{end_time}}</h4>
    </div>
    <div id="mainbody-title-right">
        <form id="mainbody-title-time-query" method="post" action="{% url query_url %}">
            {% csrf_token %}
            <span>Change query time:</span>
            <div id="from-datetime"><span>from</span>
                <select class='select-year' name='from-year'></select>
                <select class='select-month' name='from-month'></select>
                <select class='select-day' name='from-day'></select>
                <select class='select-hour' name='from-hour'></select>
                :
                <select class='select-minute' name='from-minute'></select>
                :
                <select class='select-second' name='from-second'></select>
            </div>
            <div id="to-datetime"><span>  to  </span>
                <select class='select-year' name='to-year'></select>
                <select class='select-month' name='to-month'></select>
                <select class='select-day' name='to-day'></select>
                <select class='select-hour' name='to-hour'></select>
                :
                <select class='select-minute' name='to-minute'></select>
                :
                <select class='select-second' name='to-second'></select>
            </div>
            <input id="submit-button" type="submit" value="query">
            <script>
                $("#submit-button").click(function() {
                    start_time = 
                        $("#from-datetime").find(".select-year").val() + '-' + 
                        $("#from-datetime").find(".select-month").val() + '-' + 
                        $("#from-datetime").find(".select-day").val() + ' ' +
                        $("#from-datetime").find(".select-hour").val() + ':' +
                        $("#from-datetime").find(".select-minute").val() + ':' +
                        $("#from-datetime").find(".select-second").val();
                    end_time = 
                        $("#to-datetime").find(".select-year").val() + '-' + 
                        $("#to-datetime").find(".select-month").val() + '-' + 
                        $("#to-datetime").find(".select-day").val() + ' ' +
                        $("#to-datetime").find(".select-hour").val() + ':' +
                        $("#to-datetime").find(".select-minute").val() + ':' +
                        $("#to-datetime").find(".select-second").val();
                })
            </script>
        </form>
    </div>
</div>

web_module/myids/templates/myids/stat.html
{% load static %}
<html>
    <head>
        <title>myids</title>
        <link rel="stylesheet" type="text/css" href="{% static 'myids/css/highcharts.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'myids/css/header.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'myids/css/mainbody-title.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'myids/css/table.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'myids/css/pagin.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'myids/css/stat.css' %}">

        <script src="{% static 'myids/js/resource/jquery.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'myids/js/resource/highcharts.js' %}" type="text/javascript"></script>

        <script src="{% static 'myids/js/render.js' %}" type="text/javascript"></script>
        <script src="{% static 'myids/js/queryStat.js' %}" type="text/javascript"></script>
        <script src="{% static 'myids/js/pagin.js' %}" type="text/javascript"></script>
        <script src="{% static 'myids/js/select_datetime.js' %}" type="text/javascript"></script>
        <script src="{% static 'myids/js/stat_switch.js' %}" type="text/javascript"></script>
        <script>
            var start_time = "{{start_time}}";
            var end_time = "{{end_time}}";
            var query_stat_url = "{% url 'myids:query_stat' %}";
            var conn_url = "{% url 'myids:conn' %}";
            var overviewPageSize = 6;
            var detailPageSize = 10;
        </script>
        
    </head>

    <body>

        <!-- header -->
        {% include 'myids/header.html' %}

        <!--main body-->
        {% include 'myids/mainbody-title.html' with title_name='Statistics' query_url='myids:stat' %}

        <div id="mainbody-switch">
            <ul>
                <li class="mainbody-switch-item" id="alert-switch">alert</li>
                <li class="mainbody-switch-item" id="proto-switch">proto</li>
                <li class="mainbody-switch-item" id="src_ip-switch">src_ip</li>
                <li class="mainbody-switch-item" id="dest_ip-switch">dest_ip</li>
                <li class="mainbody-switch-item" id="src_port-switch">src_port</li>
                <li class="mainbody-switch-item" id="dest_port-switch">dest_port</li>
            </ul>
        </div>

        <div id="mainbody-panel">
            <div id="stat-overview-panel">
                <span id="stat-overview-title"></span>
                <div class="chart-container">
                    <div class="pie-container" id="stat-pie-container"></div>
                    <div class="line-container" id="stat-line-container"></div>
                </div>
                <div id="stat-overview-container">
                    <table id="stat-overview-table">
                        <thead></thead>
                        <tbody></tbody>
                    </table>
                    <div class="pagination"></div>
                </div>
            </div>
        
            <div id="stat-detail-panel">
                <div id="stat-detail-header">
                    <span id="stat-detail-title"></span>
                    <span class="back-button">back to overview</span>
                </div>
                <div id="stat-detail-container">
                    <table id="stat-detail-table">
                        <thead></thead>
                        <tbody></tbody>
                    </table>
                    <div class="pagination"></div>
                </div>
            </div>
        
            <script>
                $("#stat-detail-panel").hide();
                $("#stat-overview-title").text("Alert overview (Charts show only top 10)");
                loadPie("stat-pie-container", "alert");
                loadLine("stat-line-container", "alert");
                loadStatOverview($("#stat-overview-table"), "alert", 1, overviewPageSize);
                $(".back-button").click(function () {
                    var detailPanel = $("#stat-detail-panel");
                    var overviewPanel = $("#stat-overview-panel");
                    detailPanel.hide();
                    overviewPanel.show();
                });
            </script>
            
        
        </div>

    </body>
</html>